export const DICT: Record<string, string> = {
  i: "je",
  you: "tu/vous",
  he: "il",
  she: "elle",
  we: "nous",
  they: "ils/elles",
  a: "un/une",
  an: "un/une",
  the: "le/la",
  and: "et",
  or: "ou",
  but: "mais",
  to: "à",
  for: "pour",
  of: "de",
  in: "dans",
  on: "sur",
  at: "à",
  with: "avec",
  without: "sans",
  please: "s’il vous plaît",
  ticket: "billet",
  return: "aller-retour",
  coffee: "café",
  wake: "me réveille",
  up: "(particule) / en haut",
  early: "tôt",
  make: "prépare / fait",
  would: "(conditionnel)",
  like: "aimer",
  london: "Londres",
  meeting: "réunion",
  ten: "dix",
  "o'clock": "heures",
  there: "il y a",
  three: "trois",
  questions: "questions",
  test: "test / examen",
  small: "petit",
  apartment: "appartement",
  dinner: "dîner",
  family: "famille",
};
export function translateWord(w: string): string {
  const clean = w.toLowerCase().replace(/[^a-z'-]/g, "");
  return DICT[clean] ?? "(pas dans le dico pour l’instant)";
}
