export type FrDailyItem = { fr: string; ru?: string };

const frEveryday: FrDailyItem[] = [
  { fr: "Bonjour, comment vas-tu ?" },
  { fr: "Salut, ça va ?" },
  { fr: "Bonsoir, tu as passé une bonne journée ?" },
  { fr: "Merci beaucoup, c’est très gentil." },
  { fr: "Excuse-moi, je ne voulais pas te déranger." },
  { fr: "Pardon, est-ce que je peux passer ?" },
  { fr: "À bientôt, prends soin de toi !" },
  { fr: "Bonne journée, bonne soirée, bonne nuit." },
  { fr: "Tu as bien dormi cette nuit ?" },
  { fr: "Qu’est-ce qu’on mange ce soir ?" },
  { fr: "Tu peux mettre la table s’il te plaît ?" },
  { fr: "J’ai besoin de faire une lessive." },
  { fr: "On sort les poubelles demain matin." },
  { fr: "Tu peux fermer la fenêtre, il fait froid." },
  { fr: "Tu as vu mes clés ? Je ne les trouve pas." },
  { fr: "La télécommande est où ?" },
  { fr: "J’ai faim, qu’est-ce qu’on prépare ?" },
  { fr: "Tu veux un café ou un thé ?" },
  { fr: "Passe-moi le sel, s’il te plaît." },
  { fr: "Tu as envie de dessert ?" },
  { fr: "Je fais les courses demain, il te faut quelque chose ?" },
  { fr: "Attention, c’est chaud !" },
  { fr: "Tu veux goûter ?" },
  { fr: "C’est délicieux, tu as bien cuisiné !" },
  // courses / boutique
  { fr: "Bonjour, je voudrais une baguette, s’il vous plaît." },
  { fr: "Combien ça coûte ?" },
  { fr: "Est-ce que vous avez une taille plus grande ?" },
  { fr: "Je peux payer par carte ?" },
  { fr: "Vous ouvrez à quelle heure demain ?" },
  { fr: "Excusez-moi, où se trouve le rayon des fruits ?" },
  { fr: "Merci, bonne journée." },
  // transports
  { fr: "Le bus passe toutes les combien de minutes ?" },
  { fr: "Je prends le métro à la prochaine station." },
  { fr: "Excusez-moi, pour aller à la gare ?" },
  { fr: "Vous descendez au prochain arrêt ?" },
  { fr: "On se retrouve devant l’entrée principale." },
  { fr: "Je dois acheter un billet aller-retour." },
  { fr: "Il y a beaucoup de circulation aujourd’hui." },
  // communication
  { fr: "Allô, tu m’entends bien ?" },
  { fr: "Je te rappelle plus tard." },
  { fr: "Tu peux m’envoyer un message quand tu arrives ?" },
  { fr: "J’ai raté ton appel, excuse-moi." },
  { fr: "Tu as reçu mon mail ?" },
  { fr: "Envoie-moi la photo sur WhatsApp." },
  { fr: "On se fait une visio ce soir ?" },
  // travail / études
  { fr: "Tu as terminé ton dossier ?" },
  { fr: "J’ai une réunion à 14h." },
  { fr: "Peux-tu m’expliquer encore une fois ?" },
  { fr: "On fait une pause café ?" },
  { fr: "J’imprime les documents et je te les apporte." },
  { fr: "Je vais travailler de chez moi aujourd’hui." },
  { fr: "On révise ensemble demain ?" },
  // social / sorties
  { fr: "Tu veux venir dîner à la maison ce week-end ?" },
  { fr: "On va au cinéma ce soir ?" },
  { fr: "Tu as déjà vu ce film ?" },
  { fr: "Ça te dit d’aller boire un verre ?" },
  { fr: "J’ai une super nouvelle à t’annoncer !" },
  { fr: "Je suis désolé(e), je ne peux pas venir." },
  { fr: "Joyeux anniversaire !" },
  { fr: "On se fait une balade cet après-midi ?" },
  // réactions / humeur / météo
  { fr: "Ça marche !" },
  { fr: "Pas de souci." },
  { fr: "C’est pas grave." },
  { fr: "Tant mieux !" },
  { fr: "Tu plaisantes ?" },
  { fr: "Je suis crevé(e)." },
  { fr: "Il fait un temps magnifique !" },
  { fr: "J’ai trop de choses à faire aujourd’hui." },
];

export default frEveryday;
