export type FrExamItem = { fr: string; ru: string };

const frExams: FrExamItem[] = [
  { fr: "Lis attentivement le texte suivant et réponds aux questions.", ru: "Прочитайте внимательно следующий текст и ответьте на вопросы." },
  { fr: "Expliquez avec vos propres mots.", ru: "Объясните своими словами." },
  { fr: "Justifiez votre réponse.", ru: "Обоснуйте свой ответ." },
  { fr: "Donnez un exemple précis.", ru: "Приведите конкретный пример." },
  { fr: "Citez deux arguments du texte.", ru: "Приведите две аргумента из текста." },
  { fr: "Résumez ce passage en quelques lignes.", ru: "Кратко перескажите этот отрывок." },
  { fr: "Quelle est l’idée principale du document ?", ru: "Какова основная идея документа?" },
  { fr: "Dégagez la problématique du sujet.", ru: "Выделите проблематику темы." },
  { fr: "Montrez en quoi ce texte est actuel.", ru: "Покажите, в чём актуальность этого текста." },
  { fr: "Quelle conclusion peut-on tirer de ce texte ?", ru: "Какой вывод можно сделать из этого текста?" },
  { fr: "À votre avis, quelle est la solution ?", ru: "По вашему мнению, какое решение?" },
  { fr: "Développez votre opinion en 10 lignes.", ru: "Развивайте своё мнение в десяти строках." },
  { fr: "Comparez les deux documents.", ru: "Сравните два документа." },
  { fr: "Relevez les différences et les ressemblances.", ru: "Отметьте различия и сходства." },
  { fr: "Analysez la structure du texte.", ru: "Проанализируйте структуру текста." },
  { fr: "Décrivez la scène représentée.", ru: "Опишите представленную сцену." },
  { fr: "Interprétez le comportement du personnage.", ru: "Интерпретируйте поведение персонажа." },
  { fr: "Quelles sont les causes et les conséquences ?", ru: "Каковы причины и последствия?" },
  { fr: "Quels sont les avantages et les inconvénients ?", ru: "Каковы преимущества и недостатки?" },
  { fr: "Expliquez pourquoi l’auteur utilise ce mot.", ru: "Объясните, почему автор использует это слово." },
  { fr: "Donnez un synonyme du terme souligné.", ru: "Дайте синоним подчеркнутого термина." },
  { fr: "Trouvez un antonyme du mot donné.", ru: "Найдите антоним данного слова." },
  { fr: "Remplacez ce mot par un autre de même sens.", ru: "Замените это слово другим со схожим значением." },
  { fr: "Conjuguez le verbe au temps demandé.", ru: "Проспрягайте глагол в требуемом времени." },
  { fr: "Transformez cette phrase à la forme négative.", ru: "Преобразуйте это предложение в отрицательную форму." },
  { fr: "Passez cette phrase au pluriel.", ru: "Поставьте это предложение во множественное число." },
  { fr: "Mettez la phrase à la forme interrogative.", ru: "Сделайте это предложение вопросительным." },
  { fr: "Écrivez un texte de dix lignes sur ce sujet.", ru: "Напишите текст из десяти строк на эту тему." },
  { fr: "Rédigez une lettre officielle.", ru: "Составьте официальное письмо." },
  { fr: "Rédigez un courrier électronique.", ru: "Напишите электронное письмо." },
  { fr: "Rédigez un dialogue.", ru: "Составьте диалог." },
  { fr: "Faites un résumé en 5 lignes.", ru: "Сделайте краткое изложение в пять строк." },
  { fr: "Décrivez une image en dix phrases.", ru: "Опишите картинку в десяти предложениях." },
  { fr: "Rédigez une introduction et une conclusion.", ru: "Напишите введение и заключение." },
  { fr: "Trouvez un titre au document.", ru: "Найдите название документа." },
  { fr: "Quelle est la thèse défendue par l’auteur ?", ru: "Какова тезис автора?" },
  { fr: "Relevez trois arguments utilisés.", ru: "Приведите три аргумента." },
  { fr: "Montrez la stratégie de persuasion.", ru: "Покажите стратегию убеждения." },
  { fr: "Identifiez le registre du texte.", ru: "Определите стиль текста." },
  { fr: "Quel est le point de vue de l’auteur ?", ru: "Какова точка зрения автора?" },
  { fr: "Rédigez un paragraphe argumenté.", ru: "Напишите аргументированный абзац." },
  { fr: "Établissez un plan détaillé.", ru: "Составьте подробный план." },
  { fr: "Trouvez la morale de l’histoire.", ru: "Найдите мораль истории." },
  { fr: "Analysez le rôle du narrateur.", ru: "Проанализируйте роль рассказчика." },
  { fr: "Montrez la fonction du personnage principal.", ru: "Покажите функцию главного персонажа." },
  { fr: "Quelle figure de style est employée ?", ru: "Какая используется фигура речи?" },
  { fr: "Expliquez la métaphore.", ru: "Объясните метафору." },
  { fr: "Donnez la définition de l’hyperbole.", ru: "Дайте определение гиперболы." },
  { fr: "Identifiez le champ lexical dominant.", ru: "Определите доминирующее лексическое поле." },
  { fr: "Soulignez les adjectifs qualificatifs.", ru: "Подчеркните прилагательные." },
  { fr: "Relevez tous les verbes conjugués.", ru: "Найдите все спряжённые глаголы." },
  { fr: "Trouvez les compléments d’objet direct.", ru: "Определите прямые дополнения." },
  { fr: "Mettez les mots dans l’ordre correct.", ru: "Поставьте слова в правильном порядке." },
  { fr: "Complétez le texte avec les mots proposés.", ru: "Дополните текст предложенными словами." },
  { fr: "Choisissez la bonne réponse parmi les quatre propositions.", ru: "Выберите правильный ответ из четырёх вариантов." },
  { fr: "Cochez la case correcte.", ru: "Отметьте правильный вариант галочкой." },
  { fr: "Reliez les colonnes.", ru: "Соедините колонки." },
  { fr: "Classez les phrases dans le bon ordre.", ru: "Расположите предложения в правильном порядке." },
  { fr: "Écrivez le mot manquant.", ru: "Впишите недостающее слово." },
  { fr: "Réécrivez la phrase sans faute.", ru: "Перепишите предложение без ошибок." },
  { fr: "Corrigez les erreurs d’orthographe.", ru: "Исправьте орфографические ошибки." },
  { fr: "Transformez la phrase à la voix passive.", ru: "Преобразуйте предложение в страдательный залог." },
  { fr: "Écrivez un paragraphe au conditionnel.", ru: "Напишите абзац в условном наклонении." },
  { fr: "Rédigez un texte au futur simple.", ru: "Составьте текст в будущем времени." },
  { fr: "Écrivez au passé composé.", ru: "Напишите в прошедшем сложном времени (passé composé)." },
  { fr: "Utilisez le plus-que-parfait.", ru: "Используйте предпрошедшее время (plus-que-parfait)." },
  { fr: "Écrivez un dialogue au présent.", ru: "Составьте диалог в настоящем времени." },
  { fr: "Donnez votre avis en commençant par « je pense que ».", ru: "Выразите своё мнение, начиная с «я думаю, что»." },
  { fr: "Argumentez en trois parties.", ru: "Аргументируйте в трёх частях." },
  { fr: "Développez votre idée avec un exemple.", ru: "Развивайте свою идею с примером." },
  { fr: "Concluez par une ouverture.", ru: "Закончите открытием (связью с другой темой)." },
];

export default frExams;
